### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [4]:
import numpy as np
list_ = ["1","2","3","4","5" ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))
# As we can see from the output that list_ is a mornal list with the dimension of 1D otherthen array_list is an nDimensional list means we can create a list of dimension 1,2,3,4,5...n

<class 'list'>
<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [12]:
for i in array_list:
    print(i.dtype)
for i in list_:
    print(type(i))

int64
int64
int64
int64
int64
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


### Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [13]:
import numpy as np
list_ = ["1","2","3","4","5" ]
array_list = np.array(object = list_ , dtype=int)
print("datatype for each element present in array_list")
for i in array_list:
    print(i.dtype)
print("datatype for each element present in list_")
for i in list_:
    print(type(i))
# As we can see after giving an argument dtype = int in array_list variable the datatype for each element in both the variable list_ and array_list will get changed

datatype for each element present in array_list
int64
int64
int64
int64
int64
datatype for each element present in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


### Q4. Write a code to find the following characteristics of variable, num_array: (i) shape (ii) size

In [16]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(num_list)
print(num_array.shape)# gives the dimensionality of an list
print(num_array.size)# gives the no element present in a list

(2, 3)
6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [18]:
arr = np.zeros([3,3],dtype = int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [24]:
arr = np.identity(5,dtype = int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [22]:
arr = np.diag([1,1,1,1,1,])                                                                         
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])